# Nombre del archivo Java
JAVA_FILE = Laberinto.java

# Nombre del archivo compilado
CLASS_FILE = Laberinto.class

# Comando para compilar el programa Java
compile:
	javac $(JAVA_FILE)

# Comando para ejecutar el programa Java
run:
	java Laberinto

# Comando para limpiar los archivos compilados
clean:
	rm -f $(CLASS_FILE)
